version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
executor: machine
jobs:
  build:
    machine:
      image: circleci/classic:latest

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx5G
      TERM: dumb

    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew build jacocoTestReport --stacktrace
      - codecov/upload:
          file: talaiot/build/reports/jacoco/test/*.xml
      - store_test_results:
          path: talaiot/build/reports/tests/
      - store_artifacts:
          path: talaiot/build/reports/tests/

  deploy-snapshot:
    working_directory: ~/repo
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: snapshot
          command: ./gradlew publishMavenPublicationToSnapshotsRepository

workflows:
  version: 2
  deploy-snapshot:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
