version: 2
executorType: machine
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest


    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew build

      - store_test_results:
          path: talaiot/build/reports/tests/
      - store_artifacts:
          path: talaiot/build/reports/tests/


