version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: assemble
          command: gradle assemble
      - run:
          name: clean
          command: gradle clean